const allsongs = [
    "-Olf5QcA6PY.mp3",
    "1 HourBest Nightcore Songs Mix 2021  Best of EDM Mix 2021.mp3",
    "10convert.com_Ava-Max-Sweet-but-Psycho-Lyrics_Ot_sMK4rVqs.mp3",
    "A.B. Original - That's Love (NBA 2K22 Soundtrack).mp3 by Zaity.mp3",
    "A527-728h5c.mp3",
    "Alan Walker & Sia - Faded + Cheap Thrills + Alive + Airplanes (ft. Hayley Williams, B.o.B, S. Paul).mp3",
    "Alan Walker - Alone (WildVibes Remix) _SUPPORTED BY TIËSTO & THE CHAINSMOKERS_.mp3",
    "Albanian Remix ⚡-- [ Dj Gimi-O Habibi ] tiktok--(MP3_160K).mp3",
    "Alessia Cara - Here (Lucian Remix)(MP3_160K).mp3",
    "Alexander Rybak – Fairytale (LYRICS)(MP3_160K).mp3",
    "Alice Merton – No Roots (Lyrics)(MP3_160K).mp3",
    "Arcade - Duncan Laurence _LYRICS_ __WINNER ESC 2019__(MP3_70K).mp3",
    "asanrap - Шома тигр (bot kak to take).mp3",
    "Ava Max - Salt (Lyrics).mp3",
    "Ava Max - So Am I (Lyrics).mp3",
    "Ava Max - Sweet but Psycho (Lyrics).mp3",
    "AViVA - GRRRLS (Lyrics).mp3",
    "Axel Johansson - Do Or Die (Thopiax Remix).mp3",
    "Ayzha Nyree - Noya (Official Audio)(MP3_160K).mp3",
    "Bamboleo x Narcos (Nalo Remix)(MP3_160K).mp3",
    "Bars No Jutsu (AMV) Louis Capone(MP3_160K).mp3",
    "blackbear - hot girl bummer [Low Budget Video](MP3_160K).mp3",
    "Bruno Mars_ Anderson .Paak_ Silk Sonic - Skate (Lyrics)(MP3_160K).mp3",
    "BTvGkDga-rI.mp3",
    "bülow – Sweet Little Lies (Lyrics).mp3",
    "Camila Cabello - Don_t Go Yet (Lyrics)(MP3_160K).mp3",
    "Can_t Hold Us [Southend Revolution Remix] (ft. Ray Dalton) [Bass Boosted] - Macklemore _ Ryan Lewis(MP3_160K).mp3",
    "Cheat Codes No Promises Lyrics ft Demi Lovato.mp3",
    "CKay - Love Nwantiti (Lyrics).mp3",
    "Clara Mae - Lost (Lyrics).mp3",
    "Confetti - Ghost(MP3_160K).mp3",
    "Croosh - R.I.P(MP3_70K).mp3",
    "DaBaby - Red Light Green Light (Lyrics)(MP3_160K).mp3",
    "Daya - New (Lyrics).mp3",
    "Daya New Lyrics.mp3",
    "Desiigner - Panda (Official Audio)(MP3_160K).mp3",
    "Discover the top streamed music and songs online on Soundcloud.mp3",
    "Drive Forever - Russian Slowed Remix (English Lyrics) _ Dior Положение TikTok Remix(MP3_160K).mp3",
    "Eminem - Venom(MP3_160K).mp3",
    "Fade.mp3",
    "Feeling Good - Michael Buble (Lyrics on screen)(MP3_160K).mp3",
    "FRIENDS.mp3",
    "Future - Mask Off (Lyrics _ Lyric Video)(MP3_160K).mp3",
    "GkSmUE0eQv4.mp3",
    "GSGAmbGjFPs.mp3",
    "Gw7NujpEXRc.mp3",
    "Halsey & Khalid - Eastside (Lyrics).mp3",
    "Halsey-Khalid-Eastside-Lyrics_vON10XxQNsg.mp3",
    "i5axVy3OfGg.mp3",
    "idfc slowed - blackbear (Lyrics) _I_m only a fool for you_ [TikTok Remix](MP3_160K).mp3",
    "Illenium - It's All on U (feat. Liam O'Donnell).mp3",
    "Jon Lajoie - Everyday Normal Guy 2 [Legendado_Tradução] [PTBR](MP3_160K).mp3",
    "KALEO - Way Down We Go (Official Music Video)(MP3_160K).mp3",
    "Konfuz _ Ратата (Mood video)(MP3_160K).mp3",
    "Kyle Exum -  Bassthoven (lyrics)(MP3_160K).mp3",
    "Legends Never Die [Alan Walker Remix] _ Worlds 2017 - League of Legends.mp3",
    "Lil Nas X - MONTERO (Call Me By Your Name) (Lyrics)(MP3_160K).mp3",
    "Lil Nas X_ Jack Harlow - INDUSTRY BABY (Official Video)(MP3_160K).mp3",
    "MACKLEMORE _ RYAN LEWIS - THRIFT SHOP FEAT. WANZ (OFFICIAL VIDEO)(MP3_160K).mp3",
    "Marshmello & Anne-Marie - FRIENDS (Lyric Video) !OFFICIAL FRIENDZONE ANTHEM.mp3",
    "Marshmello, CHVRCHES - Here With Me (Lyrics).mp3",
    "Martin Jensen & James Arthur - Nobody (Lyrics).mp3",
    "Masked Wolf - Astronaut In The Ocean (Official Music Video)(MP3_160K).mp3",
    "MC L da Vinte _ MC Gury – Parado no Bailão (مترجمة)(MP3_160K).mp3",
    "Migos_ KAROL G_ Snoop Dogg _ Rock Mafia – My Family (_The Addams Family_ OST) (Lyrics_ Letra)(MP3_160K).mp3",
    "Måneskin - Beggin_ (Lyrics)(MP3_160K).mp3",
    "Måneskin - I WANNA BE YOUR SLAVE (Lyrics_Testo)(MP3_160K).mp3",
    "Måneskin - New Song (Lyrics)(MP3_160K).mp3",
    "Måneskin - Somebody Told Me (Lyrics)(MP3_160K).mp3",
    "n2ieHzLPzog.mp3",
    "NEFFEX - Fight Back [Official Video](MP3_160K).mp3",
    "NF - CLOUDS(MP3_160K).mp3",
    "NF - DRIFTING (Audio)(MP3_160K).mp3",
    "NF - LOST ft. Hopsin(MP3_160K).mp3",
    "NF - TRUST (Audio) ft. Tech N9ne(MP3_160K).mp3",
    "Nightcore - Bad Girl.mp3",
    "Nightcore - Castle.mp3",
    "Nightcore - Dear 16 Year Old Me.mp3",
    "Nightcore - First.mp3",
    "Nightcore - Living Legend.mp3",
    "Nightcore - MAYDAY.mp3",
    "Nightcore - Play Date 💘.mp3",
    "Nightcore - Roses.mp3",
    "Nightcore - Something Just Like This.mp3",
    "Nightcore - The Spectre.mp3",
    "Nightcore - We Don't Sleep At Night → Switching Vocals.mp3",
    "Nightcore - Zombie.mp3",
    "nightcore masked wolf.mp3",
    "Nightcore → Dreams pt. II.mp3",
    "Nightcore → Hiding In The Blue.mp3",
    "Nightcore → Mama Told Me (NMV).mp3",
    "nightCore.mp3",
    "nightcores.mp3",
    "Panic_ At The Disco - The Greatest Show (from The Greatest Showman_ Reimagined) [Official Audio](MP3_160K).mp3",
    "Pharrell Williams - Happy (Official Music Video)(MP3_160K).mp3",
    "Play - Alan Walker, K-391, Tungevaag, Mangoo.mp3",
    "Pop Smoke _ Travis Scott - Creature x 5_ TINT(tiktok remix)(MP3_160K).mp3",
    "pxHHiZ_EsbI.mp3",
    "reversed-Konfuz _ Ратата (Mood video)(MP3_160K).mp3",
    "reversed-weired-Lil Nas X_ Jack Harlow - INDUSTRY BABY (Official Video)(MP3_160K).mp3",
    "RIVER - BISHOP BRIGGS (summer raeann)(MP3_160K).mp3",
    "Russ Millions x Tion Wayne - Body (Lyrics)(MP3_160K).mp3",
    "S-LvVdZq_so.mp3",
    "Salvatore Ganacci - Baby i got issues but i love myself (Talk) (Lyrics)(MP3_160K).mp3",
    "Selena Gomez - Back To You (Lyrics).mp3",
    "Shaun Frank - Let You Get Away (ft. Ashe) (Nolan van Lith Remix).mp3",
    "Sing Me To Sleep (Marshmello Remix).mp3",
    "Smoove L - New Apolos [BEGINNING LOOPED](MP3_160K).mp3",
    "Smoove_l - Apollo (Tik-tok)(MP3_160K).mp3",
    "song.mp3",
    "song_2.mp3",
    "song_3.mp3",
    "SQWOZ BAB_ THE FIRST STATION _ АУФ (Lyric video)(MP3_160K).mp3",
    "Stay.mp3",
    "Symphony (feat. Zara Larsson).mp3",
    "Talk (Tiktok Remix) [Lyrics] _ i was busy thinking about_ baby i got issues but i love myself(MP3_160K).mp3",
    "tempted remix (feat. juice wrld) [kid cudi vibes] by Dj Tam (ig- @tameralexandere).mp3",
    "Tesher - Jalebi Baby (Lyrics )(MP3_160K).mp3",
    "The Kid LAROI - WITHOUT YOU (Official Video)(MP3_160K).mp3",
    "The Kid LAROI_ Justin Bieber - Stay (Lyrics)(MP3_160K).mp3",
    "Thrift Shop - Bass Boosted(MP3_160K).mp3",
    "Thunder Lyrics  مترجمه _ Imagine Dragons(MP3_160K).mp3",
    "Tory Lanez Let it Loose remix by Ill Neptune freestyle(MP3_160K).mp3",
    "Trinidad Cardona - Dinero (Lyrics) _ She take my dinero(MP3_160K).mp3",
    "Twenty One Pilots - Heathens (DISTO Remix).mp3",
    "ULlwaDaEXeE.mp3",
    "Unlike Pluto - No Scrubs ft. Joanna Jones (Cover)(MP3_70K).mp3",
    "Wolves.mp3",
    "اغنية (Wellerman) مترجمة للعربية _ (Lyric) _ [مع كلمات الأغنية باللغة الإنجليزية](MP3_160K).mp3"
]